server:
  port: 6060
  servlet:
    contextPath: /eureka
eureka:
  instance:
    #hostname: localhost
    hostname: 63.250.55.150
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    fetch-registry: false
    register-with-eureka: false

spring:
  profiles:
    active: dev
  security:
    basic:
      enabled: true
      #user:
      #name: swipeuser
      #password: swipepass
